### ISSUE TITLE
Errors thrown in the user panel

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#120] opened 2010-05-03 02:42 UTC
http://forums.anodyne-productions.com/viewtopic.php?f=60&t=2944

**Comment by anodyne** [comment] 2010-05-04 12:49
Requested more information since there's no way the library should be throwing this error

**Comment by agentphoenix** [comment] 2010-07-25 14:08
Closing because I can't reproduce the issue.

**Closed as completed by agentphoenix** 2010-07-25 14:08 UTC
Labels: bug
