### ISSUE TITLE
Advanced wiki page protection

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#11] opened 2009-11-24 04:50 UTC
We should be able to set wiki page protection based on person or role, be it editing or viewing

**Comment by agentphoenix** [comment] 2010-09-18 02:41
Can this be tied in to the work on #12?

**Comment by agentphoenix** [comment] 2010-12-29 19:39
Closing this since it is pretty much a duplicate of #12.

**Closed as completed by agentphoenix** 2010-12-29 19:39 UTC
Labels: forums, feature request
