### ISSUE TITLE
Approving Pending Posts not emailing correctly

### ISSUE THREAD

**Issue by greenfelt22** [anodyne/nova#295] opened 2020-09-24 18:42 UTC
When a GM/Moderator "approves" a post in pending status, a character attributed to the moderator is the namesake applied to the post when emailed. Post authorship doesn't change, just the name of the person doing the approval.

Email example:
![image](https://user-images.githubusercontent.com/25126048/94185960-ab78d500-fe6b-11ea-9df6-dfbdae83a1cd.png)

Published example from website:
![image](https://user-images.githubusercontent.com/25126048/94186019-bb90b480-fe6b-11ea-8bc3-37aca8a1a75a.png)

**Comment by agentphoenix** [comment] 2020-10-06 14:00
@greenfelt22 I'm not sure I'm following what the issue is.

**Comment by greenfelt22** [comment] 2020-10-06 14:07
When an unmoderated post is published, the "From" field on the email takes on the name of a character of a person that wrote the post. In the above example, the post was written by a player's PC and NPC. The PC, Major Bayushi, would normally be the name that would show up as who the post is from in the email notification.

When a post is moderated however... A member of command team reviews the post and then approves it. On the site, it shows correctly. However, when the email is sent, instead of grabbing the character name from the actual post authors, it grabs the name of the moderator who is approving the post. In the above example, Ensign Loren Kita is a character associated with the moderator who approved the post. That player and character was not involved in writing the post, but the email notification is indicating otherwise. The website correctly maintains authorship.

**Comment by agentphoenix** [comment] 2020-12-30 14:50
@greenfelt22 Found the issue. It'll be fixed in the next Nova release.

**Closed as completed** 2022-03-24 14:10 UTC
Labels: bug, fixed
